#!/usr/bin/env bash
set -euo pipefail

deb=~/Downloads/discord.deb

wget -O "$deb" "https://discord.com/api/download/stable?platform=linux&format=deb"

if [ -f "$deb" ]; then
    sudo dpkg -i "$deb"
    rm "$deb"
else
    echo "Failed to download Discord."
fi
